apiVersion: v1
kind: Service
metadata:
  name: hello-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    hello: web
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30001
