apiVersion: v1
kind: Service
metadata:
  name: hello-server
  namespace: {{ .Values.namespace }}
  labels:
    app: hello-server
spec:
  type: NodePort
  selector:
    app: hello-server
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: {{ .Values.service.port }}
